Vans
slim1979/ttd pull request #5
Opened 2017-08-13 10:19 UTC by slim1979

2017-08-13 10:23 UTC, vkurennov requested changes

2017-08-13 10:23 UTC, vkurennov commented on app/models/van.rb
> +  validates :kind, presence: true
В моделях пишутся сначала ассоциации, потом - валидации

2017-08-13 10:23 UTC, vkurennov commented on app/views/vans/_coupe_vans.html.erb
> +    <li>Верхних: <%= @all = 0; @coupe_vans.each{ |van| @all += van.up_seats }; @all %></li>
Не нужно ничего считать в видах, сделай методы в моделях и вызывай их тут.

2017-08-13 10:23 UTC, vkurennov commented on app/views/vans/_form.html.erb
> +    <%= form.text_field :kind, id: :van_kind %>
Лучше сделать выпадающий список

2017-08-13 10:28 UTC, slim1979 commented on app/models/van.rb
> +  validates :kind, presence: true
точно

2017-08-13 10:28 UTC, slim1979 commented on app/views/vans/_form.html.erb
> +    <%= form.text_field :kind, id: :van_kind %>
так и думал)

2017-08-13 10:28 UTC, slim1979 commented on app/views/vans/_coupe_vans.html.erb
> +    <li>Верхних: <%= @all = 0; @coupe_vans.each{ |van| @all += van.up_seats }; @all %></li>
ок

2017-08-14 09:05 UTC, vkurennov approved these changes

2017-08-14 09:48 UTC, merged